workflows:
  android-build-v2:
    name: Android Build - THE SOURCE
    instance_type: mac_mini_m1
    max_build_duration: 60
    integrations:
      # Autorización de GitHub para acceso al repositorio
      - github

    environment:
      # Definición del ambiente base
      node: 16.18.0 # Versión estable de Node.js que no da conflicto (la que forzamos antes)
      xcode: 14.3.1 # Versión segura para SDK 49 de Expo
      
    scripts:
      - name: Instalar Herramientas (EAS CLI)
        script: npm install -g eas-cli
      
      - name: Instalar Dependencias Locales
        script: |
          npm install
          npx expo prebuild --platform android --clean
      
      - name: Build and Sign APK
        script: |
          eas build --profile production --platform android --non-interactive
          
    artifacts:
      - build/app/build/outputs/apk/**/*.apk
    
    triggering:
      events:
        - push
      branch:
        - main
